### PR TITLE
QEMU 8.2.0 with support for SEV-SNP + IGVM

### PR DESCRIPTION
**Pull request by roy-hopkins**
This provides a version of QEMU that supports IGVM launch of coconut-SVSM with a linux guest that works with the v6.8-rc3 kernel (in a [separate PR](https://github.com/coconut-svsm/linux/pull/2)).

This version of QEMU is based on [this AMD branch](https://github.com/AMDESE/qemu/tree/snp-v3-wip) which was referred to in the [[PATCH v11] Add AMD Secure Nested Paging (SEV-SNP) Hypervisor Support patch series](https://lore.kernel.org/kvm/20231230172351.574091-1-michael.roth@amd.com/). In addition, the IGVM patches from the current [QEMU SVSM IGVM branch](https://github.com/coconut-svsm/qemu/tree/svsm-igvm) have been applied with some fixups and tidy-ups.

This version of QEMU only supports launching coconut-SVSM using IGVM.

### CODE REVIEW

**Comment by cclaudio** [comment]
Thanks @roy-hopkins . I am testing the vtpm patches with this and the linux PR.
Would you have instructions on how to launch the coconut-svsm using IGVM?

**Comment by roy-hopkins** [comment]
> Thanks @roy-hopkins . I am testing the vtpm patches with this and the linux PR. Would you have instructions on how to launch the coconut-svsm using IGVM?

I'm using a script to launch the guest which ends up with a command similar to this. You'll have to update the image and IGVM file paths.

```
sudo qemu-system-x86_64 
    -enable-kvm 
    -cpu EPYC-v4 
    -machine q35,confidential-guest-support=sev0,memory-backend=mem0 
    -object memory-backend-memfd,size=8G,id=mem0,share=true,prealloc=false,reserve=false 
    -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,igvm-file=bin/coconut-qemu.igvm 
    -smp 4 
    -no-reboot 
    -netdev user,id=vmnic -device e1000,netdev=vmnic,romfile= 
    -drive file=[path-to-svsm.qcow2],if=none,id=disk0,format=qcow2,snapshot=on 
    -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=on 
    -device scsi-hd,drive=disk0,bootindex=0 
    -nographic 
    -monitor none 
    -serial stdio 
    -serial pty
```

**Comment by cclaudio** [comment]
Hi @roy-hopkins, I am still testing this PR, but I would like to give you some feedback in advance. 

1) After following the instructions in [#237](https://github.com/coconut-svsm/svsm/pull/237), the qemu cmdline below is failing for me with the error message "qemu-system-x86_64: Property 'pc-q35-8.2-machine.kvm-type' not found".

```
sudo $HOME/src/coconut/build/qemu/bin/qemu-system-x86_64 \
  -enable-kvm \
  -cpu EPYC-v4 \
  -machine q35,confidential-guest-support=sev0,memory-backend=ram1,kvm-type=protected \
  -object memory-backend-memfd,id=ram1,size=8G,share=true,prealloc=false,reserve=false \
  -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,igvm-file=bin/coconut-qemu.igvm \
  -smp 4 \ 
  -no-reboot \
  -netdev user,id=vmnic -device e1000,netdev=vmnic,romfile= \
  -kernel $HOME/src/coconut/linux/guest/arch/x86/boot/bzImage \
  -initrd $HOME/src/coconut/initrd/initrd-test.img \
  -append "console=ttyS0 earlyprintk=serial loglevel=8 rdinit=/bin/bash" \
  -nographic \
  -monitor none \
  -serial stdio \
  -serial pty
```

2)  Should this be based on the QEMU [svsm-preview-v4](https://github.com/AMDESE/qemu/tree/svsm-preview-v4) rather than the snp-v3-wip?

**Comment by roy-hopkins** [comment]
> 1. After following the instructions in [#237](https://github.com/coconut-svsm/svsm/pull/237), the qemu cmdline below is failing for me with the error message "qemu-system-x86_64: Property 'pc-q35-8.2-machine.kvm-type' not found".

You should just remove `kvm-type=protected` from the `-machine` line. See my example above.

> 2. Should this be based on the QEMU [svsm-preview-v4](https://github.com/AMDESE/qemu/tree/svsm-preview-v4) rather than the snp-v3-wip?

I based it on the version that was referred to in the host SEV-SNP patch series here: https://lore.kernel.org/kvm/20231230172351.574091-1-michael.roth@amd.com/

I'll take a look to see what has changed between this and v4 as it probably makes sense to use that as the latest.

**Comment by cclaudio** [comment]
Thanks @roy-hopkins.

I am getting a different error when I remove `kvm-type=protected`:
`qemu-system-x86_64: vm-type snp not supported by KVM`.

As an experiment, I commented out the `exit(1)` line related to the error message above and got a another interesting error message:
`qemu-system-x86_64: KVM doesn't support guest memfd`

I am running [this kernel PR](https://github.com/coconut-svsm/linux/pull/2) on both host and guest. I noticed that the kernel PR cherry picks some patches from the AMD linux `svsm-preview-host-v4` and `svsm-preview-guest-v4` branches. I am wondering if those v4 patches are compatible with this qemu PR (based on the AMD qemu `snp-v3-wip`). Maybe @tlendacky can tell us if the mentioned AMD branches are compatible.

**Comment by roy-hopkins** [comment]
> I am getting a different error when I remove `kvm-type=protected`: `qemu-system-x86_64: vm-type snp not supported by KVM`.
> 
> As an experiment, I commented out the `exit(1)` line related to the error message above and got a another interesting error message: `qemu-system-x86_64: KVM doesn't support guest memfd`

Have you enabled `CONFIG_KVM_AMD_SEV` in the kernel config? I'm using exactly the same host/guest kernel as you as well as this version of QEMU. They are definitely compatible with each other. I'll check what the difference is between `snp-v3-wip` and `snp-preview-v4`, but the reason `snp-v3-wip` was used is that it is the version referred to in the AMD host patch series.

**Comment by cclaudio** [comment]
It looks like there is something wrong in my environment, I will double check it. Thank you so much.

**Comment by cclaudio** [comment]
Worked for me with the [linux PR #2](https://github.com/coconut-svsm/linux/pull/2). Thank you.

**Comment by roy-hopkins** [comment]
> Worked for me with the [linux PR #2](https://github.com/coconut-svsm/linux/pull/2). Thank you.

Great! Thank you very much for testing this.

**Comment by joergroedel** [comment]
Latest changes merged. Closing this one.

**Pull request closed without merging**
