### PR TITLE
Update to QEMU 9.0 including IGVM v4 patch series + direct VMSA

### PR DESCRIPTION
**Pull request by roy-hopkins**
## Overview
This branch is based on QEMU master commit 1a2d52c7fc with the IGVM patch series v4 applied. Also, the top commit provides a modification to the handling of IGVM VMSA directives to directly set the VMSA in KVM via the KVM_SEV_SNP_LAUNCH_UPDATE ioctl.

## Compatibility
This version of QEMU works with the host kernel in the kvm 'next' branch: https://git.kernel.org/pub/scm/virt/kvm/kvm.git/log/?h=next. However, the change to VMSA handling requires a corresponding patch to the kernel. In order to support SVSM, a further set of patches are also required.

A kernel based on kvm/next including SVSM, SEV-SNP VMPL2 guest and VMSA patches will be provided via a PR in COCONUT-SVSM/linux.

## Reason for direct VMSA update
The patch that updates VMSA handling can be dropped from this branch and SVSM will still work correctly. However, due to the way the VMSA is handled for each vCPU in KVM this will result in the launch measurement never matching the pre-calculated launch measurement of the IGVM file. The previous SVSM kernel included a sev_feature flag that indicated use of an SVSM which then changed this behaviour to get the measurement to match but this cannot be supported anymore.

## New Command line
The QEMU command line to launch a guest with SVSM has changed since the previous version. In particular `init-flags` is not supported anymore (which is how we used to indicate an SVSM was present) and IGVM now has its own object:

```
...
-machine q35,confidential-guest-support=sev0,memory-backend=mem0,igvm-cfg=igvm0 \
-object memory-backend-memfd,size=8G,id=mem0,share=true,prealloc=false,reserve=false \
-object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1 \
-object igvm-cfg,id=igvm0,file=coconut-qemu.igvm \
...
```

### CODE REVIEW

**Comment by osteffenrh** [comment]
Hi @roy-hopkins,

just testing out this PR.
It crashes trying to convert an invalid memory regrion:
```
...
[SVSM] VMSA PA: 0x8000f32000
[SVSM] Launching Firmware
[SVSM] Launching request-processing task on CPU 0
[SVSM] Failed to launch /init
SecCoreStartupWithStack(0xFFFCC000, 0x820000)
qemu-system-x86_64: Convert non guest_memfd backed memory region (0xfee00000 ,+ 0x1000) to private
EAX=00000000 EBX=00000000 ECX=00000000 EDX=00800f12
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=0000fff0 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 0000ffff 00009300
CS =f000 ffff0000 0000ffff 00009b00
SS =0000 00000000 0000ffff 00009300
DS =0000 00000000 0000ffff 00009300
FS =0000 00000000 0000ffff 00009300
GS =0000 00000000 0000ffff 00009300
LDT=0000 00000000 0000ffff 00008200
TR =0000 00000000 0000ffff 00008b00
GDT=     00000000 0000ffff
IDT=     00000000 0000ffff
CR0=60000010 CR2=00000000 CR3=00000000 CR4=00000000
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000000
Code=c5 5a 08 2d e9 22 ff 90 90 90 90 90 00 00 00 00 56 54 46 00 <0f> 20 c0 a8 01 74 05 e9 21 ff ff ff e9 01 ff 90 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```
I am using the latest main branch of Coconut, ivgm 0.3.3, Qemu from this PR, Linux from https://github.com/coconut-svsm/linux/pull/6, and the current EDK2 branch for coconut.

Any idea what might go wrong here?

Qemu command line:
```build/bin/qemu-system-x86_64 \
  -enable-kvm -cpu EPYC-v4 -smp 4 \
  -machine q35,confidential-guest-support=sev0,memory-backend=mem0,igvm-cfg=igvm0 \
  -object memory-backend-memfd,size=8G,id=mem0,share=true,prealloc=false,reserve=false \
  -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1 \
  -object igvm-cfg,id=igvm0,file=./svsm/bin/coconut-qemu.igvm \
  -no-reboot \
  -drive file=[...],if=none,id=disk0,format=qcow2,snapshot=on \
  -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true \
  -device scsi-hd,drive=disk0 \
  -nic user,model=virtio-net-pci,hostfwd=tcp::5522-:22 \
  -nographic -serial stdio -monitor none -serial unix:./svsm-gdb,server=on,wait=off
```

**Comment by roy-hopkins** [comment]
> Hi @roy-hopkins,
> 
> just testing out this PR. It crashes trying to convert an invalid memory regrion:
>
> [snip]
>
> I am using the latest main branch of Coconut, ivgm 0.3.3, Qemu from this PR, Linux from [coconut-svsm/linux#6](https://github.com/coconut-svsm/linux/pull/6), and the current EDK2 branch for coconut.
> 
> Any idea what might go wrong here?

I think you need to use the latest version of OVMF from tianocore/edk2 as the current coconut version does not seem to be compatible with the latest SEV-SNP host changes.

Try building the latest master branch: https://github.com/tianocore/edk2.

**Comment by osteffenrh** [comment]
Yes, that works. Thanks!

**Comment by aospan** [comment]
Apologies for the confusion. Will this PR be merged? Or is it recommended to use https://github.com/roy-hopkins/qemu/tree/igvm_master_v5?

Thank you!

**Comment by roy-hopkins** [comment]
Superseded by https://github.com/coconut-svsm/qemu/pull/16

**Pull request closed without merging**
